apiVersion: addons.sigs.k8s.io/v1alpha1
kind: ConfigManagement
metadata:
  name: config-management
  namespace: config-management-system
spec:
  clusterName: example-cluster-to-sync-crds
  git:
    syncRepo: git@github.com:linde/nomos-acme-corp.git
    secretType: ssh
    policyDir: config-root
    syncBranch: nomos-spark-crd
